server:
  port: 1141
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vi_job?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&connectTimeout=5000&socketTimeout=5000&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


vi-job:
  mode: cluster
  dataDir: /tmp/server1
  inetutils:
    ip-address: 127.0.0.1
  cluster:
    nodes: 127.0.0.1:2141,127.0.0.1:2142,127.0.0.1:2143

